### ISSUE TITLE
How to visualize the pretrained model？

### ISSUE THREAD

**Issue by Baozao-99** [TimFelixBeyer/weakly-supervised-cad-retrieval#3]
Hello，
If I have a .binvox or obj model and Shapnet dataset.
Could you please tell me how to use your retrieval method to find a CAD model？
I want to use the pretrained models。
![屏幕截图 2023-05-08 173953](https://user-images.githubusercontent.com/57311717/236791199-6a117b8e-a685-4ee8-8de4-ed0e2ebd74cc.jpg)
something like this
![屏幕截图 2023-05-08 173953](https://user-images.githubusercontent.com/57311717/236791918-d2867e08-a4f3-4073-9d3c-be99af2c49f9.jpg)
how do you achieve that？

**Comment by TimFelixBeyer** [comment]
These were rendered in Blender, which is a free open-source 3D program that has a python scripting interface.
