### ISSUE TITLE
Code for the inference of single point clouds

### ISSUE THREAD

**Issue by Pamogar** [TimFelixBeyer/weakly-supervised-cad-retrieval#4]
First of all, thank you for your excellent work and for releasing it as open source. 

I am working on the virtualization of 3D scenes and wanted to test your method for the CAD retrieval. I was wondering if you could facilitate a code to process a single pointcloud, in order to properly test its performance and implement it with custom point clouds.

Thank you!

**Comment by Baozao-99** [comment]
I have the same question. I think we should try to change the code in baselines/common.py, if you find a right way , please tell me.

**Comment by TimFelixBeyer** [comment]
This method is voxel-based, so you'd have to convert the point cloud into a `32x32x32` voxel representation first, then feed it to the model. Maybe the `mesh_to_voxel` function will be helpful.

**Comment by Pamogar** [comment]
Thank you for your reply.

I have been working with the code, and as you explained, using the mesh_to_voxel function, I have made it work with my custom bounding boxes and scenes. 

I have an additional question about the pretrained models. Could you explain the difference between the seen and unseen checkpoints? I can't seem to find the difference in the paper.

Thank you again!

**Comment by TimFelixBeyer** [comment]
No worries!
In the paper we report results for seen (Scan-CAD-Similarity Dataset) and unseen classes (Scan2CAD) and the checkpoints correspond to each scenario.

**Comment by Pamogar** [comment]
So the seen checkpoint is only trained with the Scan-CAD Object Similarity Dataset and the unseen one uses Scan2CAD plus the previous?

**Comment by TimFelixBeyer** [comment]
The datasets have different train/val/test splits which overlap so to ensure no contamination we only trained seen on SCOSD and unseen on Scan2CAD, using the appropriate splits. This is described in a bit more detail on page 9. I hope that helps!

**Comment by Pamogar** [comment]
Thanks for the clarifications! Tagging this as closed.
